# Generated by Django 4.2.11 on 2024-03-22 10:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.TimeField(choices=[(datetime.time(11, 0), '11:00 AM'), (datetime.time(11, 30), '11:30 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(12, 30), '12:30 PM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(13, 30), '1:30 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(14, 30), '2:30 PM'), (datetime.time(15, 0), '3:00 PM'), (datetime.time(15, 30), '3:30 PM'), (datetime.time(16, 0), '4:00 PM'), (datetime.time(16, 30), '4:30 PM'), (datetime.time(17, 0), '5:00 PM'), (datetime.time(17, 30), '5:30 PM'), (datetime.time(18, 0), '6:00 PM'), (datetime.time(18, 30), '6:30 PM'), (datetime.time(19, 0), '7:00 PM'), (datetime.time(19, 30), '7:30 PM'), (datetime.time(20, 0), '8:00 PM'), (datetime.time(20, 30), '8:30 PM'), (datetime.time(21, 0), '9:00 PM'), (datetime.time(21, 30), '9:30 PM'), (datetime.time(22, 0), '10:00 PM')])),
                ('num_guest', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.date')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.table')),
            ],
        ),
    ]
