# Generated by Django 4.2.11 on 2024-03-23 13:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 23, 13, 52, 13, 257654, tzinfo=datetime.timezone.utc), validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 23))]),
        ),
        migrations.AlterField(
            model_name='table',
            name='booking_table',
            field=models.IntegerField(choices=[(1, 'Table 1 - 4 Guests'), (2, 'Table 2 - 2 Guests'), (3, 'Table 3 - 2 Guests'), (4, 'Table 4 - 4 Guests'), (5, 'Table 5 - 4 Guests'), (6, 'Table 6 - 8 Guests'), (7, 'Table 7 - 4 Guests'), (8, 'Table 8 - 4 Guests'), (9, 'Table 9 - 4 Guests'), (10, 'Table 10 - 4 Guests'), (11, 'Table 11 - 4 Guests'), (12, 'Table 12 - 6 Guests'), (13, 'Table 13 - 4 Guests'), (14, 'Table 14 - 6 Guests')]),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
