# Generated by Django 4.2.11 on 2024-03-22 10:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 22))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.IntegerField(choices=[(1, 'Table 1'), (2, 'Table 2'), (3, 'Table 3'), (4, 'Table 4'), (5, 'Table 5'), (6, 'Table 6'), (7, 'Table 7'), (8, 'Table 8'), (9, 'Table 9'), (10, 'Table 10'), (11, 'Table 11'), (12, 'Table 12'), (13, 'Table 13'), (14, 'Table 14')]),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
