# Generated by Django 4.2.11 on 2024-03-23 14:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_booking_date_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(choices=[(datetime.time(11, 0), '11:00 AM'), (datetime.time(11, 30), '11:30 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(12, 30), '12:30 PM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(13, 30), '1:30 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(14, 30), '2:30 PM'), (datetime.time(15, 0), '3:00 PM'), (datetime.time(15, 30), '3:30 PM'), (datetime.time(16, 0), '4:00 PM'), (datetime.time(16, 30), '4:30 PM'), (datetime.time(17, 0), '5:00 PM'), (datetime.time(17, 30), '5:30 PM'), (datetime.time(18, 0), '6:00 PM'), (datetime.time(18, 30), '6:30 PM'), (datetime.time(19, 0), '7:00 PM'), (datetime.time(19, 30), '7:30 PM'), (datetime.time(20, 0), '8:00 PM'), (datetime.time(20, 30), '8:30 PM'), (datetime.time(21, 0), '9:00 PM'), (datetime.time(21, 30), '9:30 PM'), (datetime.time(22, 0), '10:00 PM')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 23))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.IntegerField(choices=[(1, 'Table 1 - 4 Guests'), (2, 'Table 2 - 2 Guests'), (3, 'Table 3 - 2 Guests'), (4, 'Table 4 - 4 Guests'), (5, 'Table 5 - 4 Guests'), (6, 'Table 6 - 8 Guests'), (7, 'Table 7 - 4 Guests'), (8, 'Table 8 - 4 Guests'), (9, 'Table 9 - 4 Guests'), (10, 'Table 10 - 4 Guests'), (11, 'Table 11 - 4 Guests'), (12, 'Table 12 - 6 Guests'), (13, 'Table 13 - 4 Guests'), (14, 'Table 14 - 6 Guests')]),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
