# Generated by Django 4.2.11 on 2024-03-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_date_alter_booking_table_delete_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='booking_date',
        ),
    ]
