# Generated by Django 4.2.11 on 2024-03-25 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='fname',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator('[a-zA-Z]')]),
        ),
        migrations.AddField(
            model_name='booking',
            name='lname',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator('[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_guest',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
